<template>
  <card>
    <h4 slot="header" class="card-title">Edit Preference</h4>
    <form>
      <div class="row">
        <div class="col-md-5">
		  <p>Select Major</p>
		  <select id="major">
		    <option value="0"></option>
			<option value="1">Computer Science</option>
			<option value="2">Information Systems</option>
		  </select>
        </div>

        <div class="col-md-5">
          <p></br>Select Concentration</p>
            <select id="concentration">
			  <option value="0"></option>
			  <option value="1">Software Development</option>
			  <option value="2">Game Systems</option>
			  <option value="3">Business Analysis/System Analysis</option>
			  <option value="4">Business Intelligence</option>
			  <option value="5">Database Administration</option>
			  <option value="6">IT Enterprise</option>
			  <option value="7">Standard</option>
			</select>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <p></br>Select School Program</p>
          <select id="schoolProgram">
			<option value="0">Undergraduate</option>
			<option value="1">Graduate</option>
		  </select>
        </div>

      </div>
	  
	  <div class="row">
	    <div class="col-md-5">
		  <p></br>I would like to...</p>
		  <input type="radio" name="electivePreference1"/> Choose my own electives</br>
		  <input type="radio" name="electivePreference1"/> Auto-select my electives</br>
		</div>
	  </div>

	  <div class="row">
	    <div class="col-md-5">
		  <p></br>I would like to...</p>
		  <input type="radio" name="electivePreference2"/> Work collaboratively with the computer to choose my classes</br>
		  <input type="radio" name="electivePreference2"/> Have my class list generated by the computer</br>
		</div>
	  </div>
	  
	  <div class="row">
        <div class="col-md-6">
          <p></br>Number of Classes/Credit Hours Per Quarter</p>
          <select id="numClasses">
		    <option value="0"></option>
			<option value="1">1 (4 credits)</option>
			<option value="2">2 (8 credits)</option>
			<option value="3">3 (12 credits)</option>
			<option value="4">4 (16 credits)</option>
			<option value="5">5 (20 credits)</option>
		  </select>
        </div>
      </div>
	  
      <div class="text-center">
        {{ errorMessage }}
        <button type="submit" class="btn btn-info btn-fill float-right" @click.prevent="updatePreferences">
          Update Preferences
        </button>
      </div>
      <div class="clearfix"></div>
    </form>
  </card>
</template>
<script>
  import Card from 'src/components/UIComponents/Cards/Card.vue'

  const API_URL = process.env.API_URL

  export default {
    components: {
      Card
    },
    data () {
      return {
        errorMessage: '',
        user: {
          accountType: JSON.parse(window.localStorage.getItem('user')).account_type,
          email: JSON.parse(window.localStorage.getItem('user')).email,
          firstName: JSON.parse(window.localStorage.getItem('user')).first_name,
          lastName: JSON.parse(window.localStorage.getItem('user')).last_name
        }
      }
    },
    methods: {
      updatePreferences () {
        this.errorMessage = '';
        let token = window.localStorage.getItem('token')
        this.$http.post(API_URL + '/v1/auth/update_user', this.user, {
          headers: {
            Authorization: 'Token ' + token
          }
        }).then((response) => {
            window.localStorage.setItem('user', JSON.stringify(response.data.data));
            this.errorMessage = 'Success!';
            var _this = this;
            setTimeout(function(){ 
              _this.errorMessage = '';
            }, 2000);
        }).catch((errors) => {
            this.errorMessage = 'No changes made';
        })
      }
    }
  }

</script>
<style>

</style>