<template>
  <card>
    <h4 slot="header" class="card-title">Edit Profile</h4>
    <form>
      <div class="row">
        <div class="col-md-5">
          <fg-input type="text"
                    label="Account Type"
                    :disabled="true"
                    placeholder="Light dashboard"
                    v-model="user.account_type">
          </fg-input>
        </div>

        <div class="col-md-7">
          <fg-input type="email"
                    label="Email"
                    placeholder="Email"
                    v-model="user.email">
          </fg-input>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <fg-input type="text"
                    label="First Name"
                    placeholder="First Name"
                    v-model="user.first_name">
          </fg-input>
        </div>
        <div class="col-md-6">
          <fg-input type="text"
                    label="Last Name"
                    placeholder="Last Name"
                    v-model="user.last_name">
          </fg-input>
        </div>
      </div>
	  
	  <div class="row">
	    <div class="col-md-6">
		  <fg-input type="text"
					label="Change Password"
					>
		  </fg-input>
		</div>
		
		<div class="col-md-6">
		  <fg-input type="text"
					label="Confirm Password"
					>
		  </fg-input>
		</div>
	  </div>
	  
	  <div class="row">
        <div class="col-md-5">
		  <p>Select Major</p>
		  <select id="major">
		    <option value="0"></option>
			<option value="1">Computer Science</option>
			<option value="2">Information Systems</option>
		  </select>
        </div>
	  </div>
	  
	  <div class="row">
        <div class="col-md-5">
          <p></br>Select Concentration</p>
            <select id="concentration">
			  <option value="0"></option>
			  <option value="1">Software Development</option>
			  <option value="2">Game Systems</option>
			  <option value="3">Business Analysis/System Analysis</option>
			  <option value="4">Business Intelligence</option>
			  <option value="5">Database Administration</option>
			  <option value="6">IT Enterprise</option>
			  <option value="7">Standard</option>
			</select>
        </div>
      </div>

      <div class="row">
        <div class="col-md-4">
		<p></br>School Program</p>
          <fg-input type="text"
					:disabled="true"
					placeholder="Graduate">
          </fg-input>
        </div>
      </div>
	  
	  <div class="row">
	    <div class="col-md-5">
		  <p></br>I would like to...</p>
		  <input type="radio" name="electivePreference1"/> Choose my own electives</br>
		  <input type="radio" name="electivePreference1"/> Auto-select my electives</br>
		</div>
	  </div>

	  <div class="row">
	    <div class="col-md-5">
		  <p></br>I would like to...</p>
		  <input type="radio" name="electivePreference2"/> Work collaboratively with the computer to choose my classes</br>
		  <input type="radio" name="electivePreference2"/> Have my class list generated by the computer</br>
		</div>
	  </div>
	  
	  <div class="row">
        <div class="col-md-6">
          <p></br>Number of Classes/Credit Hours Per Quarter</p>
          <select id="numClasses">
		    <option value="0"></option>
			<option value="1">1 (4 credits)</option>
			<option value="2" selected>2 (8 credits)</option>
			<option value="3">3 (12 credits)</option>
			<option value="4">4 (16 credits)</option>
		  </select>
        </div>
      </div>

      <div class="text-center">
        {{ errorMessage }}
        <button type="submit" class="btn btn-info btn-fill float-right" @click.prevent="updateProfile">
          Update Profile
        </button>
      </div>
      <div class="clearfix"></div>
    </form>
  </card>
</template>
<script>
  import Card from 'src/components/UIComponents/Cards/Card.vue'

  const API_URL = process.env.API_URL

  export default {
    components: {
      Card
    },
    props: ['user'],
    data () {
      return {
        errorMessage: ''
      }
    },
    methods: {
      updateProfile () {
        this.errorMessage = '';
        let token = window.localStorage.getItem('token')
        this.$http.post(API_URL + '/v1/auth/update_user', this.user, {
          headers: {
            Authorization: 'Token ' + token
          }
        }).then((response) => {
            this.errorMessage = 'Success!';
            var _this = this;
            setTimeout(function(){ 
              _this.errorMessage = '';
            }, 2000);
        }).catch((errors) => {
            this.errorMessage = 'No changes made';
        })
      }
    }
  }

</script>
<style>

</style>
