<template>
  <card>
    <h4 slot="header" class="card-title">Edit Profile</h4>
    <form>
      <div class="row">
        <div class="col-md-6">
          <fg-input type="text"
                    label="Account Type"
                    :disabled="true"
                    placeholder="Light dashboard"
                    v-model="user.account_type">
          </fg-input>
        </div>

        <div class="col-md-6">
          <fg-input type="email"
                    label="Email"
                    placeholder="Email"
                    v-model="user.email">
          </fg-input>
        </div>
      </div>

      <div class="row">
        <div class="col-md-6">
          <fg-input type="text"
                    label="First Name"
                    placeholder="First Name"
                    v-model="user.first_name">
          </fg-input>
        </div>
        <div class="col-md-6">
          <fg-input type="text"
                    label="Last Name"
                    placeholder="Last Name"
                    v-model="user.last_name">
          </fg-input>
        </div>
      </div>
	  
	  <div class="row">
	    <div class="col-md-6">
		  <fg-input type="text"
					label="Change Password"
					>
		  </fg-input>
		</div>
		
		<div class="col-md-6">
		  <fg-input type="text"
					label="Confirm Password"
					>
		  </fg-input>
		</div>
	  </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <label class="control-label">
              Undergraduate Degree
            </label>
            <select v-model="user.undergraduate_degree" class="form-control">
              <option value="Empty"></option>
              <option v-for="item in options.undergraduate_degree" v-bind:value="item">{{item}}</option>
            </select>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label class="control-label">
              Graduate Degree
            </label>
            <select v-model="user.graduate_degree" class="form-control">
              <option value="Empty"></option>
              <option v-for="item in options.graduate_degree" v-bind:value="item">{{item}}</option>
            </select>
          </div>
        </div>
        <div class="col-md-4">
          <div class="form-group">
            <label class="control-label">
              Graduate Degree Concentration
            </label>
            <select v-model="user.graduate_degree_concentration" class="form-control">
                <option value="Empty"></option>
                <option v-for="item in concentrations" v-bind:value="item">{{item}}</option>
              </select>
          </div>
        </div>
      </div>
      <hr>
      <h4 slot="header" class="card-title">Preferences</h4>

      <div class="row">
        <div class="col-md-2">
          <label class="control-label">
            Number of Credits Per Quarter
          </label>
          <select v-model="user.number_credit_hours" class="form-control">
            <option value="0"></option>
            <option v-for="item in options.credits" v-bind:value="item">{{item}} credits</option>
          </select>
        </div>
        <div class="col-md-1"></div>
        <div class="col-md-3">
          <label class="control-label">
            Electives
          </label>
          <div>
            <input type="radio" v-model="user.elective" value="Choose my own electives" /> Choose my own electives</br>
            <input type="radio" v-model="user.elective" value="Auto-select my electives" /> Auto-select my electives</br>
          </div>
        </div>
        <div class="col-md-6">
          <label class="control-label">
            Automation
          </label>
          <div>
            <input type="radio" v-model="user.automation" value="Work collaboratively with the system to choose my classes" /> Work collaboratively with the system to choose my classes</br>
            <input type="radio" v-model="user.automation" value="Have my class list generated by the system" /> Have my class list generated by the system</br>
          </div>
        </div>
      </div>

      <div class="text-center">
        {{ errorMessage }}
        <button type="submit" class="btn btn-info btn-fill float-right" @click.prevent="updateProfile">
          Update Profile
        </button>
      </div>
      <div class="clearfix"></div>

    </form>
  </card>
</template>
<script>

  import Card from 'src/components/UIComponents/Cards/Card.vue'

  const API_URL = process.env.API_URL

  export default {
    components: {
      Card
    },
    props: ['user'],
    data () {
      return {
        errorMessage: '',
        options: {
          undergraduate_degree: ['Computer Science', 'Information Systems', 'Other'],
          graduate_degree: ['Computer Science', 'Information Systems'],
          credits: ['4', '8', '12', '16']
        }
      }
    },
    computed: {
      concentrations: function() {
        if (this.user.graduate_degree == 'Computer Science') {
          return ['Software and Systems Development', 'Theory', 'Data Science', 'Database Systems', 'Artificial Intelligence', 'Software Engineering', 'Game and Real-Time Systems', 'Human-Computer Interaction'];
        } else if (this.user.graduate_degree == 'Information Systems') {
          return ['Business Analysis/Systems Analysis', 'Business Intelligence', 'Database Administration', 'IT Enterprise Management', 'Standard'];
        } else {
          return [];
        }
      },
    },
    methods: {
      updateProfile () {
        console.log(this.user)
        this.errorMessage = '';
        this.$http.post(API_URL + '/v1/auth/update_user', this.user)
          .then((response) => {
            this.errorMessage = 'Success!';
            var _this = this;
            setTimeout(function(){ 
              _this.errorMessage = '';
            }, 2000);
        }).catch((errors) => {
            this.errorMessage = 'No changes made';
        })
      }
    }
  }

</script>
<style>

</style>
